### ISSUE TITLE
Melhorar erros retornados pelo servidor

### ISSUE THREAD

**Issue by weltonfelix** [ifpeopensource/merenda-server#14]
Nos casos em que um erro 500 é lançado, a propriedade `error.details` volta vazia já que o 
JavaScript não faz o parse do Error para string. Provavelmente seria interessante usar o `error.name` para indicar o nome do erro nos details.

**Comment by carvalhoedsonn** [comment]
No caso, é apenas para resolver o erro 500?

**Comment by carvalhoedsonn** [comment]
Outra coisa, onde o GV colocou os erros que o servidor deve retornar?

**Comment by carvalhoedsonn** [comment]
> Outra coisa, onde o GV colocou os erros que o servidor deve retornar?

Esta duvida não precisa responder, entendi errado. Os erros retornados está distribuídos pelos códigos, etc.

**Comment by carvalhoedsonn** [comment]
> Outra coisa, onde o GV colocou os erros que o servidor deve retornar?

**Comment by weltonfelix** [comment]
> No caso, é apenas para resolver o erro 500?

Ele só ocorre nos erros 500 pois é onde a exceção não é tratada.

Além disso, outra opção seria passar o `error.message` como `Internal Server Error` e o details como a real message do erro. Deixaria ainda mais descritivo, já que a mensagem que importa é que houve um erro interno no servidor.

**Comment by weltonfelix** [comment]
Para evitar expôr falhas da aplicação, concordamos pelo Discord que seria mais interessante enviar apenas o erro 500 sem sua causa. Por enquanto, podemos fazer isso utilizando apenas o `response.sendStatus(500);`.

No futuro pode ser interessante padronizar o corpo do sendStatus para JSON, já que ele envia como HTML mas a API é REST (#18). Pode ser utilizado a mesma estrutura dos outros erros:

```json
{
  "error": {
    "message": "Internal Server Error"
  }
}
```
