### ISSUE TITLE
Enviar todos os erros com corpo em JSON

### ISSUE THREAD

**Issue by weltonfelix** [ifpeopensource/merenda-server#18]
Atualmente, os erros enviados com o `response.sendStatus()` do express enviam um corpo em HTML com a mensagem de erro. (Ver #14 e #15)

Isso seria interessante caso a aplicação possuísse views HTML, mas na verdade é um API REST. Dessa forma, é preciso encontrar uma forma de padronizar os erros. Pode ser utilizada a estrutura que já vem sendo utilizada nos erros com corpo customizado:

```json
{
  "error": {
    "message": "Error Message"
  }
}
```
ou
```json
{
  "error": {
    "message": "Error Message",
    "details": {...}
  }
}
```

**Comment by Gvinfinity** [comment]
Uma forma de implementação é o override das funções padrões `sendStatus()' por meio do protótipo global.
Ver: [Documentação Express](https://expressjs.com/en/guide/overriding-express-api.html)
